[tool.poetry]
name = "cousre-job"
version = "0.1.0"
description = ""
authors = ["Nesterov-art <shadowwess@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
pandas = "^2.2.3"
flask = "^3.1.0"
openpyxl = "^3.1.5"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
